### ISSUE TITLE
Consider making util package (or quick run-down in readme)

### ISSUE THREAD

**Issue by djsegal** [tpapp/TKPappKitchenSink.jl#1]
I realize this is your personal kitchen sink.

Just based on, 

> https://discourse.julialang.org/t/how-to-display-float64-with-more-digits/5628/7

It seems like there's stuff in here that other people don't need to come up with for themselves

// I'd say gists might be nice, but it seems like you already use them for instructional material

**Comment by tpapp** [comment]
I think that a package is at least as good as a gist; code can be updated in place if necessary; and I can unit test.

I would not wish to add to the proliferation of utility packages. Maybe I will contribute to some packages. This is for experimental things that I use daily.

**Comment by djsegal** [comment]
Fair enough. Closing this.

----

Also, even though you may be against joe the schmo (i.e. @djsegal) making a util package, you should know that as a senior julia developer something you describe as:

> This is for experimental things that I use daily.

would likely be very useful for others

**Comment by tpapp** [comment]
I understand your point. However, I implicitly assume a certain level of commitment for packages I make public (and then register): I respond to issues, fix bugs, add features when possible, write documentation when it makes sense, keep up with Julia versions, etc. 

This package is for things where I don't (yet) want to take on that commitment. The code is out there, I but may break it tomorrow.

If you think that `showfull` is useful, perhaps we should find a place for it.
